cagov/innovation.ca.gov

- pages/index.html
@aaronhans removed the product roles and added the developer roles. Can you please review?
I can't remember where to go to preview changes, because when I click preview here it doesn't show me what I'm looking for. 
Thanks!
> civil service developer roles

- pages/index.html
Added "Our Partners" section
Please review and merge if looks OK @aaronhans. Thanks!
> Added Section

- pages/index.html
@aaronhans please review make sure I entered correctly. thanks!
> added role

- package-lock.json
- pages/index.html
@aaronhans I am trying to add the technical recruiter role to the hiring section, but having issues. can you please assist?
Thanks
> Technical Recruiter role

- pages/index.html
@aaronhans can you double check I did this correctly?  Thanks!
> added IT Specialist role and video

- pages/index.html
Here's the content update I mentioned this morning. Content approved by Angie and Anne.
The pieces that probably need the closest review are:
- New 3 card grid for page navigation
- Anchor links to H2s 
The rest should be copy changes. Thanks to @ZainAliDigital for assisting and showing me liveweave.com so we could look at things in realtime!
> Updating ODI homepage with 1.3 content

- .eleventy.js
Removed invalid assignment which was causing except to appear when it was not wanted
> excerpt is not the lead

- .github/workflows/eleventy_build.yml
- package-lock.json
Also try adjusting package-lock setting - testing if this build will go through.
> Update to node 16.13.2 per one hint on internet to see if it fixes build

- .github/workflows/eleventy_build_pr.yml
Add the workflow file to trigger live PR preview creation based on https://github.com/cagov/odi-engineering/wiki/Set-up-PR-preview-sites
> add build process workflow

- .github/workflows/deploy_production.yml
The deploy script has been updated to include steps to move files, recache at the new innovation.ca.gov buckets while still also deploying to existing digital.ca.gov buckets
> updated deploy script for production

- pages/_data/employees.json
> title update

- .github/workflows/deploy_production.yml
> add missing step for running tests on github actions

- pages/_data/employees.json
json doesn't like trailing commas before closing curly braces
> trailing commas removed

- pages/_data/employees.json
- pages/_includes/base-layout.njk
- pages/_includes/content.njk
- pages/_includes/single-column-conditional.njk
- pages/_includes/single-column.njk
- pages/_includes/site-header.njk
- pages/_includes/site-navigation.njk
- pages/notices.html
@aaronhans if all looks good, would you approve, but not merge? I'd like to time this to other content changes to be made in WordPress. I can do the merge when I'm ready.
> Ampersand updates in code

- pages/_data/employees.json
Removed Nathan at Chad's request
> remove former employee

- pages/_data/employees.json
Moved all 4 executives to the front of the list on the meet the team page followed by employees alphabetically based on full name
> put execs first

- pages/_includes/analytics.njk
- src/js/ga-tracking.js
Have not added an ODI-specific tracking ID yet, but will add it if/when we determine what it is.
Tested this locally, and it looks okay with Google Analytics Debugger plugin.
> Migrated to GA4 tracking, using statewide tracking.

- pages/_includes/base-layout.njk
Added state website alert code.
Site has been tested using the preview method described here.
https://github.com/cagov/odi-engineering/issues/97
> Added state website alert.

- pages/_includes/site-navigation.njk
Adding new page to the site navigation
> Navigation update - CalAcademy

- pages/_includes/site-navigation.njk
Adding Innovation Hub to site navigation
> Site naviagtion update - Innovation Hub

- pages/_data/employees.json
Removing Clara from _Meet the team_
> Meet the team update

- .github/workflows/eleventy_build_pr.yml
Fix use of UPPERCASE in branch names for PRs.
> Fix use of UPPERCASE in branch names for PRs.

- README.md
- pages/_includes/site-footer.njk
Adding link to Reports page in the site footer as part of #290
> Adding Reports to footer

- pages/_data/eleventyComputed.js
- pages/_includes/search.njk
- pages/_includes/site-header.njk
- pages/_includes/site-search.njk
OK TO PUBLISH
Initial search proof-of-concept.
Largely borrowing pre-existing code from the cannabis site.
> Site Search proof of concept

- .github/workflows/deploy_production.yml
- .github/workflows/eleventy_build_pr.yml
Interestingly, this site was not producing a robots.txt file on production, not sure how that got overlooked!
I've added one in, and added the sitemap to both PRs and production.
> Repaired robots.txt file.

- pages/blog/posts/report-to-senator.html
- src/css/_blog.scss
- src/css/index.scss
From Issue #316 
Affected pages: 
* /reports/data-strategy-report-2024/
* /reports/legislative-report-2023/
* /page-score-info/#readability
(this probably won't affect the PAR page just yet)
> Added table styling.

- pages/_data/employees.json
- Jason title update
- X link updates
> June 14 Meet the team update

- pages/blog/posts/saying-it-with-style.html
Removed broken link from blog post _Saying it with style_.
> Broken link fix

- pages/_includes/site-navigation.njk
Removing data-and-innovation-fund from the top level navigation.
BEFORE
AFTER
> Removed DIF from main site navigation.

- src/css/_blog.scss
Adding support for 'noborder' class on figure component to remove borders on blog images.
> Added support for figure.noborder.

- pages/_includes/site-navigation.njk
Adding Innovation Showcase to site navigation
> Site navigation update - Adding Innovation Showcase

- pages/_includes/site-footer.njk
Added Instagram and Youtube to the social media footer.
Links have been reordered to Barb's preference, and vertically aligned to Erica's.
> Social site additions to footer (insta & youtube)
