cagov/innovation.ca.gov

.github/workflows/deploy_production.yml

This is a new git action which will deploy the built site to an AWS environment
We are preparing to do a hosting migration from github pages to AWS for digital.ca.gov
FYI the migration steps we will be following are:
- Add build and deploy steps to all relevant branches
- Verify site is built and deployed correctly 
- Setup all S3 buckets and CloudFronts required
- Request missing https certificates from AWS
- Get new certs validated with DNS updates from CDT
- Request new DNS records
- Apply approved certs to new CloudFronts
- Request existing DNS record update so it points to AWS instead of github pages

add new deploy git action to aws

---

pages/_includes/analytics.njk
src/css/index.scss

Tested the following things on a real network on development instance and they measurably improve first contentful paint scores on slower devices
- remove font network request by hardcoding just the used glyph set
- delay GA call because it will get in the way of render otherwise even when using defer on the script tag. This was tested with live GA collection and does not prevent GA noticing traffic

speed improvements

---

.eleventy.js
pages/_includes/base-layout.njk

Add the noindex meta tag to the page if the "do-not-crawl" tag is added to the WordPress page

add do not crawl support

---

pages/_includes/base-layout.njk

Upon updating the DIF page, we discovered HTML entities were not rendering in the `<title>` tag. This PR fixes this problem.

Render HTML entities in title tag

---

pages/_includes/site-navigation.njk

Changes the "Staff and alumni" site navigation menu item to "Meet the team". Also updates the corresponding URL.
We should wait until the page is updated before we merge this PR.
We'll also need to put a redirect into the S3 bucket's static website settings, as follows.
```json
{
"Condition": {
"HttpErrorCodeReturnedEquals": "404",
"KeyPrefixEquals": "who-we-are/staff-and-alumni/"
},
"Redirect": {
"HostName": "digital.ca.gov",
"HttpRedirectCode": "302",
"Protocol": "https",
"ReplaceKeyPrefixWith": "who-we-are/meet-the-team/"
}
}
```

Change menu item to "meet the team"

---

.github/workflows/deploy_production.yml

The publishing steps to digital.ca.gov have been removed
Steps to go to innovation.ca.gov remain
We are not ready to go live but have a lot of updates to make today which we plan to go live with all together when the domain cutover is enabled tomorrow morning

remove the git action steps that go to AWS S3 digital.ca.gov bucket

---

.eleventy.js
.github/workflows/deploy_production.yml
README.md
package.json
pages/_includes/base-layout.njk
pages/manual-content/sitemap.njk

There were some references to digital.ca.gov in code, time to remove all of these in preparation for launch of site on new domain
This fixes the problem noticed yesterday with social share image from new blog post not showing up because the url was using digital.ca but we are currently only deploying to innovation.ca and we haven't enabled the full site redirect on digital.ca yet

switch remaining domain references in code

---

package.json
pages/_includes/site-footer.njk

The page feedback initial data collection system has been migrated from Azure to AWS and now has a friendly domain name under our control.
This update points the feedback widget on the ODI site to this new API

V1.0.4 new feedback domain

---

pages/blog/posts/alpha-ca-gov-product-release-1.html
pages/blog/posts/alpha-ca-gov-product-release-3.html
pages/blog/posts/alpha-ca-gov-spanish-translation.html
pages/blog/posts/and-were-in-progress.html
pages/blog/posts/done-doing-dec-16-dec-22.html
pages/blog/posts/done-doing-dec-9-dec-13.html
pages/blog/posts/done-doing-feb-10-feb-17.html
pages/blog/posts/re-imagining-ca-gov-how-can-california-government-better-serve-its-people.html

Fixing broken links and misspellings identified by SiteImprove in Alpha blog posts.

QA fixes for SiteImprove

---

wordpress/wordpress-to-github.config.json

Turning on HideAuthorName in wordpress-to-github config file, to prevent /users/ API endpoint from being read, so we can turn off this endpoint.

Turned on HideAuthorName.

---

src/css/_projects.scss

Based on Kimberly's feedback here:
https://www.figma.com/file/Dev3ulmslbUYJPkaCLDnJm/Innovation.ca.gov-screens?type=design&node-id=2581-13748&mode=design&t=1w7tx3Ox3ms0k9Kt-0
1. Removed margin from bottom of hero figure.
2. Increased spacing on top of h2s by about 2x.
3. Added 10px padding to content section to match the padding on headers and footers.
The last two fixes affect many other pages on the site (not just project pages), which have the same issues.  Please check a few other pages to confirm that these changes are desired there as well.

Three styling fixes

---

src/css/_projects.scss

Fixes #205.
The mobile responsiveness problem was caused by our implementation of the bubble points, shown below.
In some (but not all) mobile browsers, these two bubbles would lock into a row, preventing the rest of the page from shrinking. This fix helps those bubbles break into a column at smaller screen sizes.

Apply flex-wrap to bubble-points

---

src/css/_projects.scss

Addresses the concerns listed here:
https://www.figma.com/file/Dev3ulmslbUYJPkaCLDnJm/Innovation.ca.gov-screens?type=design&node-id=2631-1032&mode=design&t=k9BFaNoEAOzwPPOo-0
The flex properties of the "Project Scope" section have been altered to help out on mobile.
Before:
After:

Change flex properties of project summaries

---

pages/_includes/base-layout.njk

@mediajunkie noticed that shared links to our recent blog post were not correctly showing preview on linked in.  The linked page was [here](https://innovation.ca.gov/our-work/projects/getting-compensation-to-more-california-crime-victims/).
Inspecting the social media headers, I noticed the image links were 404ing.  
This turned out to be due to an eleventy filter, _changedomain_, which was changing the domain of the media library to innovation.ca.gov, which does not currently host the media library at the same path.  I removed the use of this filter (which was only used in the social media headers), and now the image links in the social media headers have valid URLs.
The invalid (translated) image link was: 
https://innovation.ca.gov/wp-content/uploads/2023/05/cropped-vcb-project-header-p …

Removed call to changedomain in social media headers.

---

src/css/_layouts-extra.scss
src/css/_projects.scss
src/css/_theme-overrides.scss

Adds adjustments so that left margins are aligned on most pages, addressing issue #210.
Removes an adjustment from the home-page that is now covered by site-wide styling.
BEFORE
AFTER

Issue #210. Styling tweaks to align left margin.

---

pages/_includes/base-layout.njk
src/css/_projects.scss

Tweaked branch name
In issue #212 (https://github.com/cagov/innovation.ca.gov/issues/212), Kimberly identified three issues.
1. Social media preview does not appear to be working for LinkedIn. (Fixed in my latest test)
2. Social media preview does not work for Twitter (addressed here).
3. Bubbles need a narrow margin so we can fit 3 bubbles on a line (fixed here).
There were two issues with the Twitter social media tags.  One is that twitter uses the keyword 'name' instead of 'property' in its social media meta tags, as described here.  https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started#started
Secondly, Twitter is perfectly happy to use the old school og: tags if they are provided, and we do provide them, so there is no need to provide redundant tags …

Jbum styling 4

---

.eleventy.js
pages/_includes/base-layout.njk

Currently social media images were not being translated to the ODI innovation domain, and being read directly from Pantheon.  Pantheon's default robots.txt file prevented the twitterBot from reading these images, which broke social media preview on Twitter.  This is a patch to fix this issue.

Added filter so that social-media images aren't run from Pantheon site.

---

.eleventy.js

Need to fix recent problems with site build.
```
[11ty] Unfortunately you’re using code that monkey patched some Eleventy internals and it isn’t async-friendly. Change your code to use the async `read()` method on the template instead! (via Error)
[11ty] 
[11ty] Original error stack trace: Error: Unfortunately you’re using code that monkey patched some Eleventy internals and it isn’t async-friendly. Change your code to use the async `read()` method on the template instead!
```

Fix problems with site build

---

.eleventy.js
package-lock.json
package.json
pages/_data/readability.json
scoring/readability.mjs
test/index.spec.mjs

Total change to the way we generate the `_site_dist/allFiles.json` file. This file is used for both readability scoring and tests.
It turns out 11ty gives us this file, verbatim, for free. All we need to do is write out the `results` from the `eleventy.after` event ([docs](https://www.11ty.dev/docs/events/)). 
By using 11ty's method, we avoid iterating over each page and writing out the results ourselves. Our manual iterations led to some bugs that sometimes prevented all our pages from making their way into `allFiles.json`. In turn, this is why some pages were missing their readability scores.
With this change, we can also simplify the tests a bit, also included here.

Change how we make allFiles.json

---

pages/_includes/analytics.njk

All our websites use two different GA4 ids for google analytics.  Like so:
```
gtag("config", "G-69TD0KNT0F"); // Statewide GA4 measurement ID
gtag("config", "G-70MEKX9MZC"); // innovation.ca.gov ID
```
The code we use to set up those two ids (copied from several canonical google examples) causes two separate loads of Google's tagmanager script. 
Before going crazy trying to fix this, I'd like to understand the actual effect, if any, this double load has on the page performance score.  So I am turning off one of the IDs (the statewide one) for a couple hours, so I can remeasure the site across all the pages, and measure the cumulative performance gain.  
```
// gtag("config", "G-69TD0KNT0F"); // Statewide GA4 measurement ID
gtag("config", "G-70MEKX9MZC"); // innovation.ca.gov ID
```
If it …

Google Analytics Test

---

pages/_data/eleventyComputed.js
pages/manual-content/feed.njk

Following the recent config cleanup project (#242), it looks like the wordpress-to-github process deleted our new `11tydata.js` content data files. These deletions will cause our builds and tests to fail.
(This is unexpected, because all of this worked fine on Drought.) 
In this PR, I've consolidated the `11tydata.js` files into the core, top-level `eleventyComputed.js` file, where it won't be deleted.

Fix site build

---

pages/_includes/par-scores.njk

The PAR footer is inhibited from display. It can be displayed using the ?par parameter. 
Second try at this, since I forgot that I can't use uppercase letters in PR branch names.

Removed PAR footer (second try).

---

pages/_includes/analytics-body.njk
pages/_includes/analytics-head.njk
pages/_includes/analytics.njk
pages/_includes/base-layout.njk

Based on my discussions with Regan.  We are going to start using GTM on the innovation site to give him some more tracking flexibility.  Will continue to use GA4, for now, on hub and alpha sites.

Changed to use of Google Tag Manager instead of GA4.

---

pages/_includes/par-statistics.njk

This change demonstrates how to collect all PAR scores on a page when using the newer 11ty-data-cascade-style setup for per-page scoring.
The key insight here is to take advantage of [11ty's Collections feature](https://www.11ty.dev/docs/collections/). Within a given template, this allows us to iterate over the data for many pages across the site. While it's typically useful for generating things like sitemaps or blog listings, we can also use it to list the PAR data.
This PR currently uses the generic `collections.all` built-in collection to get all pages. For more control over the list, check out the 11ty docs for more details on [how to do fine-grained filtering and sorting in a custom collection](https://www.11ty.dev/docs/collections/#advanced-custom-filtering-and-sorting).

Use 11ty collections to display all PAR data

---

.github/workflows/deploy_dev_aws.yml
.github/workflows/deploy_production.yml
.github/workflows/eleventy_build_pr.yml

The n1hility plugin we use to cancel previous runs is no longer maintained, and is using a deprecated version of node.
Since this plugin was written, github has introduced a built-in feature to handle concurrency.  
This patch uses it.
More info here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency

Replaced use of unmaintained n1hility plugin with newer concurrency feature.

---

src/css/_projects.scss

Removed overflow:hidden from bubble styling since it is unnecessary and may trigger false positives in SiteImprove

Removed overflow:hidden from bubble styling.

---

package.json
playwright.config.mjs
test/index-blog.spec.mjs
test/index.spec.mjs

There is an ongoing issue (#259) with this repo in that the tests run slowly.  When github is especially overloaded, this has occasionally caused publishing to fail.  [Here is an example run](https://github.com/cagov/innovation.ca.gov/actions/runs/7848250733/job/21418945066) where this happened last February.
This patch divides the tests into two roughly equal sized tasks that are executed in parallel.  One handles all the blog posts, and the other handles the remainder of the pages.  This should provide a significant speed up, and will (hopefully) speed up publishing.  
In the future, as the blog posts increase, we should divide the tests further, but this should be adequate for a good while.
In addition to the speed improvement, I've added the default testing directory to the playwright …

Testing speed improvement (issue #259)

---

.github/workflows/eleventy_build_pr.yml

Addresses issue #293 
Adding accessibility testing in PR builds will enable us to catch issues quickly, and avoid surprises at publish time.
It will slow down PR builds by a little over a minute.

Added accessibility testing in PR builds.

---

pages/_includes/base-layout.njk

We have not been using this field, even though Michael has been supplying it.

Corrected meta description to use SEO-supplied meta description, if supplied.

---

pages/_includes/site-header.njk
src/css/index.scss

Make search available on mobile devices.

Make search visible on mobile devices.

---

pages/_data/eleventyComputed.js
pages/manual-content/sitemap.njk

I noticed today, when testing search, that some testing pages tagged `do-not-crawl` were showing up in the site-map.
This was due to two design flaws.  The sitemap generator was not looking for these tags, and the code that surfaces the tags was not coded correctly.   
I've fixed this bug so that such pages do not show up in the sitemap.xml file.
Moreover, these pages now correctly include a `<meta name="robots" content="noindex">` tag.

Fixed sitemap to exclude pages with do-not-crawl tag. 

---

.eleventy.js
pages/_includes/all-posts.njk

Issue 45 for innovation site: https://coda.io/d/ODI-website-and-Innovation-Hub_dZn8KtPsvDo/Task-tracking_suYxMTm5#Tasks_tuPeXE43/r45
Inhibit display of blog posts older than 2022 on the blog index page.

Inhibit display of earlier-than 2022 blog posts on blog index page.

---

.github/workflows/deploy_production.yml

Added workflow-dispatch option so we can trigger re-deployments from github without making cosmetic changes or rerunning older jobs.

Added workflow-dispatch option to deployment workflow.

---

src/js/cagov-paginator.js

Smooth scroll to top when changing pages using the pagination widget.  Jeffrey's request.
https://app.asana.com/0/1208802063370031/1209079014287265/f
An open question is whether we should scroll-to-top when navigating to a prior page.  For now I'm scrolling to top regardless of the direction of travel.

Smooth scroll to top when changing pages.

---

src/css/index.scss

I added some custom classes in the wordpress markup to enable these tweaks.
BEFORE
AFTER

Styling fix to tweak alignment of engaged cal block on homepage.

---

pages/_includes/search.njk

Gabi noticed the paging numbers on the google search results are tiny.  This increases their size so they are readable, and useable on mobile.

Enlarged text and increased spacing on paging numbers.

---

.eleventy.js

I found, when diagnosing a recurring build-error on the home page (triggered by adding an &lt;a&gt; tag around an image), that some markup was getting incorrectly mangled by the eleventy build script.  The culprit was the first period in the regular expression in these lines:
```
// Replace Wordpress media paths with correct 11ty output path.
const regexPattern = `http.+?pantheonsite\.io/wp-content/uploads/`;
content = content.replace(new RegExp(regexPattern, 'g'), `/${wordpressImagePath}/`);
```
The above code appears to have been added Jan 3, 2024. The problem with it is that it even though it is set to non-greedy matching, it can trigger incorrect matches across _multiple tags on the same line_.  So for example if there is a single line that contains an &lt;a&gt; tag surrounding an …

Fix site compilation bug

---

.github/workflows/deploy_dev_aws.yml
.github/workflows/deploy_production.yml
.github/workflows/eleventy_build_pr.yml

Reduce reliance on 3rd party plugins for simple AWS tasks, for greater resiliency and reduced code size :
Eliminates use of 
* jakejarvis/s3-sync-action,
* prewk/s3-cp-action@v2, and 
* chetan/invalidate-cloudfront-action, 
...and instead runs the underlying aws cli commands directly, a feature supported by github.
Simplifies the build scripts (reduced line count), eliminating redundancy in credentials and region params.

Eliminated three 3rd party plugins in favor of aws cli commands.
